log_level = "warn"
outputs = "Active"
position = "Top"
app_launcher_cmd = "wofi --show drun"

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces", "WindowTitle" ] ]
center = [ "Clock" ]
right = [ "SystemInfo", [  "Tray", "Privacy", "KeyboardLayout", "Settings", "sysPower" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "wofi --show drun"

[[CustomModule]]
name = "sysPower"
icon = "⏻"
command = "wlogout"

[keyboard_layout.labels]
"English (US)" = "US"
"Russian" = "RU"

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
style = "Islands"
font_name = "Fira Mono"

primary_color = "#f7cf7a"
success_color = "#9ece6a"
text_color = "#d6cea9"
workspace_colors = [ "#f7cf7a", "#9ece6a" ]
special_workspace_colors = [ "#f7cf7a", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#685e41"

[appearance.secondary_color]
base = "#0c0d14"

